---
driver:
  name: vagrant
  provider: parallels

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  multiple_converge: 2
  enforce_idempotency: true
  require_chef_omnibus: true

platforms:
- name: apex/macos-10.12.6
- name: apex/macos-10.13.3

verifier:
  name: inspec

suites:
- name: default
  run_list:
  - recipe[homebrew]
  - recipe[vsts_agent_macos::vsts_agent]
  verifier:
    sudo: false
    inspec_tests:
    - test/smoke/default
  attributes:
    vsts_agent:
      agent_pool: OXO Hub Eng Mac Pool
      account: office
      data_bag: vsts
      data_bag_item: office_build_agent
    homebrew:
      auto-update: false
      owner: vagrant
    authorization:
      sudo:
        groups:
        - admin
        passwordless: true
