---
provisioner:
  product_name: chef
  install_strategy: always
  multiple_converge: 2
  enforce_idempotency: true

platforms:
- name: sierra
  driver:
    name: vagrant
    box: microsoft/macos-sierra
    box_url: http://office-infra-boxes.corp.microsoft.com:8099/microsoft/macos-sierra
    provider: parallels
    box_check_update: true

- name: high-sierra
  driver:
    name: vagrant
    box: microsoft/macos-high-sierra
    box_url: http://office-infra-boxes.corp.microsoft.com:8099/microsoft/macos-high-sierra
    provider: parallels
    box_check_update: true

verifier:
  name: inspec
  format: junit:/tmp/junit.xml
  reporter:
  - progress
  - junit:/tmp/junit.xml
  sudo: false
  inspec_tests:
  - test/integration/default

suites:
- name: build_agent
  run_list:
  - recipe[vsts_agent_macos::default]
  attributes:
    vsts_agent:
      agent_pool: ApexInfra macOS
      account: office
      data_bag: vsts
      data_bag_item: office_build_agent
      additional_environment:
        VAGRANT_SERVER_URL: http://office-infra-boxes.corp.microsoft.com
    homebrew:
      auto-update: false
      owner: vagrant

- name: deployment_target
  run_list:
  - recipe[vsts_agent_macos::default]
  attributes:
    vsts_agent:
      deployment_pool: macOS Netboot
      account: office
      data_bag: vsts
      data_bag_item: office_build_agent
      deployment_target: true
      project: APEX
      work: _work
      additional_environment:
        VAGRANT_SERVER_URL: http://office-infra-boxes.corp.microsoft.com
    homebrew:
      auto-update: false
      owner: vagrant
