---
driver:
  name: vagrant
  provider: parallels

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  require_chef_omnibus: true

platforms:
- name: apex/macos-10.12.6
- name: apex/macos-10.13.3

verifier:
  name: inspec

suites:
- name: default
  run_list:
  - recipe[vsts_agent_macos::bootstrap]
  - recipe[vsts_agent_macos::service_audit]
  - recipe[vsts_agent_macos::teardown]
  verifier:
    sudo: false
    inspec_tests:
    - test/integration/default
  attributes:
    vsts_agent:
      agent_pool: OXO Hub Eng Mac Pool
      account: office
      data_bag: vsts
      data_bag_item: office_build_agent
      additional_environment:
        VAGRANT_SERVER_URL: http://office-infra-boxes.corp.microsoft.com
        MEAL_ENDS_WITH: sauce
    homebrew:
      auto-update: false
      owner: vagrant
