---
driver:
  name: vagrant
  provider: parallels

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  multiple_converge: 3
  enforce_idempotency: true

platforms:
- name: apex/macos-10.12.6
- name: apex/macos-10.13.3

suites:
- name: default
  run_list:
  - recipe[homebrew]
  - recipe[vsts_agent_macos::vsts_agent]
  verifier:
    name: inspec
    inspec_tests:
    - test/smoke/default
  attributes:
    vsts_agent:
      admin_user: admin
      agent_pool: "OXO Hub Eng Mac Pool"
    homebrew:
      auto-update: false
      owner: admin
    authorization:
      sudo:
        groups:
        - admin
        passwordless: true
