---
provisioner:
  data_bags_path: data_bags
  enforce_idempotency: true
  install_strategy: once
  multiple_converge: 2
  product_name: chef

platforms:
- name: high-sierra
  driver:
    box: microsoft/macos-high-sierra
    box_check_update: true
    box_url: http://office-infra-boxes.corp.microsoft.com:8099/microsoft/macos-high-sierra
    name: vagrant
    provider: parallels

- name: mojave
  driver:
    box: microsoft/macos-mojave
    box_check_update: true
    box_url: http://office-infra-boxes.corp.microsoft.com:8099/microsoft/macos-mojave
    name: vagrant
    provider: parallels

verifier:
  name: inspec
  format:
  - cli
  - junit:/tmp/inspec.xml
  sudo: false
  inspec_tests:
  - test/integration/default

suites:
- name: build_agent
  run_list:
  - recipe[azure_pipelines_agent_macos::default]
  attributes:
    azure_pipelines_agent:
      agent_pool: SEAL Mac Staging
      account: office
      data_bag: azure_pipelines
      data_bag_item: office_build_agent
      additional_environment:
        VAGRANT_SERVER_URL: http://office-infra-boxes.corp.microsoft.com
    homebrew:
      auto-update: false
      owner: vagrant

- name: deployment_group
  run_list:
  - recipe[azure_pipelines_agent_macos::default]
  attributes:
    azure_pipelines_agent:
      deployment_group: Cookbook Group
      deployment_group_tags: test,kitchen,vagrant,chef
      account: office
      data_bag: azure_pipelines
      data_bag_item: office_build_agent
      project: APEX
      work: _work
      additional_environment:
        VAGRANT_SERVER_URL: http://office-infra-boxes.corp.microsoft.com
    homebrew:
      auto-update: false
      owner: vagrant
